local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"

local generatedData_era_a = {
    ["era_a_1"] = {
        models = {

        },
    },
    ["era_a_2"] = {
        models = {


        },
    },
    ["era_a_name"] = {
        models = {

        }
    },
    ["era_a_perron_assets"] = {
        models = {


        },
    },
}

function data()
    local function GetModelsConfig()
        return {
            perron = "station/rail/quai_2_simple.mdl",
            endPerron = "station/rail/quai_2_simple_end.mdl",
            era = 2,
        }
    end

    return {
        availability = {
            yearFrom = 1980,
        },
        category = {
            categories = { "platforms", "Ouest-etat" },
        },
        cost = {
            price = 18000,
        },
        description = {
            name = _("Ouest Etat Quai 2 simple"),
            -- description = _("A platform for passengers."),
            icon = "ui/construction/station/rail/quai_2.tga",
        },
        -- buildMode = "MULTI",
        type = "passenger_platform",
        order = {
            value = 703,
        },
        metadata = {
            platform = true,
            passenger_platform = true,
        },

        updateFn = function(result, transform, tag, slotId, addModelFn)
            local faces = {
                { 2.5,  -20.0, 0.0, 1.0 },
                { 2.5,  20.0,  0.0, 1.0 },
                { -2.5, 20.0,  0.0, 1.0 },
                { -2.5, -20.0, 0.0, 1.0 },
            }
            modulesutil.TransformFaces(transform, faces)
            local faces2 = { type = "EQUAL", faces = { faces } }
            table.insert(result.terrainAlignmentLists, faces2)

            table.insert(result.colliders, {
                type = "BOX",
                transf = transform,
                params = {
                    halfExtents = { 2.5, 20, 2 },
                }
            })

            table.insert(result.groundFaces, {
                face = faces,
                modes = {
                    {
                        type = "FILL",
                        key = "shared/gravel_03.gtex.lua"
                    },
                    {
                        type = "STROKE_OUTER",
                        key = "street_border.lua"
                    },
                },
            })
            local coords = result.GetCoord(slotId)
            local i = coords[1]
            local j = coords[2]

            local hasStairs = result.GetPlatformAddonAt(i, j) and result.GetPlatformAddonAt(i, j).metadata.underground

            if not hasStairs then
                result.models[#result.models + 1] = {
                    id = "station/rail/era_a/tn_underground_connection.mdl",
                    transf = transf.mul(transform, transf.transl(vec3.new(0, 0, 0))),
                    tag = tag
                }

                local modelsConfig = GetModelsConfig()
                addModelFn(modelsConfig.perron, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)),
                    "perron" .. i .. "_" .. j)
                --addModelFn(modelsConfig.perronRoof, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)))

                local tran = transf.mul(transform, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)))

                local num1 = #result.models
                result.addPlatformCallback(i, j, function(left, n, station)
                    local ns = tostring(n)
                    if result.labelText[num1] == nil then result.labelText[num1] = { "", "", "", "" } end
                    if left then
                        result.labelText[num1][3] = ns
                        result.labelText[num1][4] = ns
                    else
                        result.labelText[num1][1] = ns
                        result.labelText[num1][2] = ns
                    end
                    local stationS = tostring(station)
                    result.labelText[num1 + 1] = { stationS, stationS }
                    result.labelText[num1 + 2] = { stationS, stationS }
                end)

                local nextM = result.GetModuleAt(i, j - 1)
                local ca = (nextM and (nextM.metadata.passenger_platform or nextM.metadata.cargo_platform)) or
                    result.connector[1000 * i + 100 * (j - 1) + 7]
                if not ca then
                    addModelFn(modelsConfig.endPerron, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)))
                    --addModelFn(modelsConfig.endPerronRoof, transf.rotZTransl(math.rad(-90), vec3.new(0, -20, 0)))
                end
                local prevM = result.GetModuleAt(i, j + 1)
                local cb = (prevM and (prevM.metadata.passenger_platform or prevM.metadata.cargo_platform)) or
                    result.connector[1000 * i + 100 * (j + 1) + 0]
                if not cb then
                    addModelFn(modelsConfig.endPerron, transf.rotZTransl(math.rad(90), vec3.new(0, 20, 0)))
                    --addModelFn(modelsConfig.endPerronRoof, transf.rotZTransl(math.rad(90), vec3.new(0, 20, 0)))
                end
            end
        end,

        getModelsFn = function()
            local modelsConfig = GetModelsConfig()
            local result = {
                {
                    id = modelsConfig.perron,
                    transf = transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)),
                },
                {
                    id = modelsConfig.endPerron,
                    transf = transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)),
                },
                {
                    id = modelsConfig.endPerron,
                    transf = transf.rotZTransl(math.rad(90), vec3.new(0, 20, 0)),
                },
                -- {
                -- id = modelsConfig.perronRoof,
                -- transf = transf.rotZTransl(math.rad(90), vec3.new(0,-20,0)),
                -- },
                -- {
                -- id = modelsConfig.endPerronRoof,
                -- transf = transf.rotZTransl(math.rad(-90), vec3.new(0,-20,0)),
                -- },
                -- {
                -- id = modelsConfig.endPerronRoof,
                -- transf = transf.rotZTransl(math.rad(90), vec3.new(0,20,0)),
                -- },
            }

            return result
        end
    }
end
