local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local oppiestationhelper = require "modules/OUESTstationhelper"

local generatedData_era_a = {
	["era_a_1"] = {
		models = {

		},
	},
	["era_a_2"] = {
		models = {
		
		
		},
	},
	["era_a_name"] = {
		models = {
			
		}
	},
	["era_a_perron_assets"] = {
		models = {
			
			
		},
	},
}

function data()
    local function GetModelsConfig()
        return {
            perron = "station/rail/asset/quai/quai_3/quai_3_perron.mdl",
			endPerron = "station/rail/asset/quai/quai_3/quai_3_perron_end.mdl",
			tracksidePerron = "station/rail/asset/quai/quai_3/quai_3_trackside.mdl",
			endCap2 = "station/rail/asset/quai/quai_3/quai_3_endcap2.mdl",
			fenceCorner = "station/rail/asset/quai/quai_3/quai_3_endcap4.mdl",
			endCap = "station/rail/asset/quai/quai_3/quai_3_endcap.mdl",
			endCapSmall = "station/rail/asset/quai/quai_3/quai_3_endcap3.mdl",
			endCapStair = "station/rail/asset/quai/quai_3/quai_3_endcapstair.mdl",
			endCapHeadStair = "station/rail/asset/quai/quai_3/quai_3_head_stair.mdl",
			tracksidePerronEndCapLeft = "assets/empty.mdl",
			tracksidePerronEndCapRight = "assets/empty.mdl",
			propNameBoard = "assets/panneau/panneau_sncf_2011_poteau_double.mdl",
			propNameBoard2 = "assets/panneau/panneau_sncf_2011_poteau_double.mdl",
			propLamppost = "station/rail/asset/quai/props/lampadaire_generique_ouest.mdl",
			propPlatformnumber = "station/rail/asset/quai/props/panneau_voie.mdl",
		    era = 0,
        }
    end

	return {
		availability = {
			yearFrom = 1980,
			yearTo = 0
		},
		cost = {
			price = -1,
		},
		category = {
			categories = { "platforms", "Gares Type Ouest-Etat - Quai"},
		},
		description = {
			name = _("Quai type 3"),
			--description = _("A Dutch-style platform for passengers."),
			icon = "ui/construction/station/rail/quai_3.tga",
		},
		type = "passenger_platform",
		order = {
			value = 1,
		},
		metadata = {
			platform = true,
			passenger_platform = true,
			oppie_ns_platform = false,
		},
		updateFn = function (result, transform, tag, slotId, addModelFn)
			local faces = {
				{2.5,  -20.0, 0.0, 1.0},
				{2.5,  20.0,  0.0, 1.0},
				{-2.5, 20.0,  0.0, 1.0},
				{-2.5, -20.0, 0.0, 1.0},
			}

			modulesutil.TransformFaces(transform, faces)
			local faces2 = { type = "EQUAL", faces = { faces } }
			table.insert(result.terrainAlignmentLists, faces2)

			table.insert(result.colliders, {
				type = "BOX",
				transf = transform,
				params = {
					halfExtents = { 1.5, 20, 2 },
				}
			})

			table.insert(result.groundFaces, {  
				face = faces,
				modes = {
					{
						type = "FILL",
						key = "shared/gravel_03.gtex.lua"
					},
					{
						type = "STROKE_OUTER",
						key = "street_border.lua"
					},
				},
			})

			local coords = result.GetCoord(slotId)
			local i = coords[1]
			local j = coords[2]

			local platformInfo = oppiestationhelper.getPlatformInfo(result, i, j)

			if not platformInfo.addon then
					result.models[#result.models + 1] = { 
						id = "station/rail/era_a/tn_underground_connection.mdl",
						transf = transf.mul(transform, transf.transl(vec3.new(0, 0, 0))),
						tag = tag
					}
			
				local modelsConfig = GetModelsConfig()
				addModelFn(modelsConfig.perron, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)), "perron" .. i .. "_" .. j)
			
				local tran = transf.mul(transform, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)))
			
				local num1 = #result.models
				result.addPlatformCallback(i, j, function(left, n, station)
					local ns = tostring(n)
					if left then
						result.labelText[num1 + 1] = {ns,ns}
					else
						result.labelText[num1 + 2] = {ns,ns}
					end
					local stationS = tostring(station)
					result.labelText[num1 + 3] = {stationS,stationS}

					
				end)				
				
				-- place all label containers first				
				oppiestationhelper.addLabelContainers(platformInfo, addModelFn, modelsConfig, -0.5, 0, -10 , j)				
				oppiestationhelper.addLampposts(platformInfo, addModelFn, -0.5, 10, -10)

				addModelFn(modelsConfig.tracksidePerron, transf.rotZTransl(math.rad(-90), vec3.new(-2.65, 0, 0.01)))
				addModelFn(modelsConfig.tracksidePerron, transf.rotZTransl(math.rad(90), vec3.new(2.65, 0, 0.01)))

				
				local nextM = result.GetModuleAt(i,j-1)
				local ca =  (nextM and (nextM.metadata.passenger_platform or nextM.metadata.cargo_platform)) or  result.connector[1000 * i + 100 * (j-1) + 7]
				if not ca then
					addModelFn(modelsConfig.endPerron, transf.rotZTransl(math.rad(0), vec3.new(0, -20, 0.01)))
					--addModelFn(modelsConfig.endPerronRoof, transf.rotZTransl(math.rad(-90), vec3.new(0, -20, 0)))
				end
				local prevM = result.GetModuleAt(i,j+1)
				local cb = (prevM and (prevM.metadata.passenger_platform or prevM.metadata.cargo_platform)) or  result.connector[1000 * i + 100 * (j+1) + 0]
				if not cb then
					addModelFn(modelsConfig.endPerron, transf.rotZTransl(math.rad(180), vec3.new(0, 20, 0.01)))
					--addModelFn(modelsConfig.endPerronRoof, transf.rotZTransl(math.rad(90), vec3.new(0, 20, 0)))
				end
			
			end
		end,
		getModelsFn = function()
			local modelsConfig = GetModelsConfig()
			local result = {
				{ 
					id = modelsConfig.perron,
					transf = transf.rotZTransl(math.rad(90), vec3.new(0,-20,0)),
				},
				{ 
					id = modelsConfig.endPerron,
					transf = transf.rotZTransl(math.rad(0), vec3.new(0, -20, 0.001)),
				},
				{ 
					id = modelsConfig.endPerron,
					transf = transf.rotZTransl(math.rad(180), vec3.new(0, 20, 0.001)),
				},
				
			}
			
			return result
		end
	}
end