local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local oppiestationhelper = require "modules/OUESTstationhelper"

function data()
    local function GetModelsConfig()
        return {
            perronRoof = "station/rail/asset/hauvent/hauvent_1.mdl",			
            perronRoofOverpass = "station/rail/asset/hauvent/hauvent_1_overpass.mdl",			
		    era = 0,
        }
    end

	return {
		availability = {
			yearFrom = 1980,
			yearTo = 0
		},
		cost = {
			price = -1,
		},
		category = {
			categories = { "misc", "Gares Type Ouest-Etat - Hauvent"},
		},
		description = {
			name = _("Hauvent 1"),
			--description = _("A Dutch-style platform for passengers."),
			icon = "ui/construction/station/rail/hauvent_1.tga",
		},
		type = "passenger_platform_roof",
		order = {
			value = 1,
		},
		metadata = {
			platform_roof = true,
		},
		updateFn = function (result, transform, tag, slotId, addModelFn)
			local modelsConfig = GetModelsConfig()
			
			local coords = result.GetCoord(slotId)
			local i = coords[1]
			local j = coords[2]

			local platformInfo = oppiestationhelper.getPlatformInfo(result, i, j)

			if platformInfo.isOverpass and platformInfo.isOverpassReverse then
				addModelFn(modelsConfig.perronRoofOverpass, transf.rotZTransl(math.rad(-90), vec3.new(0, 0, -0.5)))
			elseif platformInfo.isOverpass and (not platformInfo.isOverpassReverse) then
				addModelFn(modelsConfig.perronRoofOverpass, transf.rotZTransl(math.rad(-90), vec3.new(0, 0, -0.5)))
			else
				addModelFn(modelsConfig.perronRoof, transf.rotZTransl(math.rad(-90), vec3.new(0, 0, -0.5)))
			end
		end,
		getModelsFn = function()
			local modelsConfig = GetModelsConfig()
			local result = {
				{ 
					id = modelsConfig.perronRoof,
					transf = transf.rotZTransl(math.rad(-90), vec3.new(0,0,0)),
				},
			}
			
			return result
		end
	}
end